# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0002_auto_20160202_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
