# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0010_image_blue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='blue',
        ),
    ]
