# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-09 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0011_remove_image_blue'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hsvHist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
