# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0013_example_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Classifier',
        ),
        migrations.AddField(
            model_name='example',
            name='label',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
