# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0014_auto_20160216_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='lbpHist',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
