# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0015_image_lbphist'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='correlation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='dissimilarity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
