# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbir', '0016_auto_20160223_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='correlation',
        ),
        migrations.RemoveField(
            model_name='image',
            name='dissimilarity',
        ),
        migrations.AddField(
            model_name='image',
            name='texture',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='bgrHist',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='hsvHist',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
